//
// Generated file, do not edit! Created by opp_msgtool 6.0 from carla/platooning/messages/ExitRequest.msg.
//

#ifndef __EXITREQUEST_M_H
#define __EXITREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ExitRequest;
#include "plexe/messages/ManeuverMessage_m.h" // import plexe.messages.ManeuverMessage

/**
 * Class generated from <tt>carla/platooning/messages/ExitRequest.msg:3</tt> by opp_msgtool.
 * <pre>
 * packet ExitRequest extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class ExitRequest : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const ExitRequest& other);

  protected:
    bool operator==(const ExitRequest&) = delete;

  public:
    ExitRequest(const char *name=nullptr, short kind=0);
    ExitRequest(const ExitRequest& other);
    virtual ~ExitRequest();
    ExitRequest& operator=(const ExitRequest& other);
    virtual ExitRequest *dup() const override {return new ExitRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ExitRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ExitRequest& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ExitRequest *fromAnyPtr(any_ptr ptr) { return check_and_cast<ExitRequest*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __EXITREQUEST_M_H

