//
// Generated file, do not edit! Created by opp_msgtool 6.0 from carla/platooning/messages/ExitAck.msg.
//

#ifndef __EXITACK_M_H
#define __EXITACK_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class ExitAck;
#include "plexe/messages/ManeuverMessage_m.h" // import plexe.messages.ManeuverMessage

/**
 * Class generated from <tt>carla/platooning/messages/ExitAck.msg:3</tt> by opp_msgtool.
 * <pre>
 * packet ExitAck extends ManeuverMessage
 * {
 * }
 * </pre>
 */
class ExitAck : public ::ManeuverMessage
{
  protected:

  private:
    void copy(const ExitAck& other);

  protected:
    bool operator==(const ExitAck&) = delete;

  public:
    ExitAck(const char *name=nullptr, short kind=0);
    ExitAck(const ExitAck& other);
    virtual ~ExitAck();
    ExitAck& operator=(const ExitAck& other);
    virtual ExitAck *dup() const override {return new ExitAck(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ExitAck& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ExitAck& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline ExitAck *fromAnyPtr(any_ptr ptr) { return check_and_cast<ExitAck*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __EXITACK_M_H

