//
// Generated file, do not edit! Created by opp_msgtool 6.0 from carla/msg/CarlaManeuverMessage.msg.
//

#ifndef __CARLAMANEUVERMESSAGE_M_H
#define __CARLAMANEUVERMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class CarlaManeuverMessage;
// cplusplus {{
#include <vector>
// }}

/**
 * Enum generated from <tt>carla/msg/CarlaManeuverMessage.msg:6</tt> by opp_msgtool.
 * <pre>
 * enum CarlaManeuverType
 * {
 *     JOIN_REQ = 1;
 *     JOIN_RSP = 2;
 *     MOVE_TO_POS = 3;
 *     MOVE_TO_POS_ACK = 4;
 *     JOIN_FORMATION = 5;
 *     JOIN_FORMATION_ACK = 6;
 *     UPDATE_FORMATION = 7;
 * }
 * </pre>
 */
enum CarlaManeuverType {
    JOIN_REQ = 1,
    JOIN_RSP = 2,
    MOVE_TO_POS = 3,
    MOVE_TO_POS_ACK = 4,
    JOIN_FORMATION = 5,
    JOIN_FORMATION_ACK = 6,
    UPDATE_FORMATION = 7
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CarlaManeuverType& e) { b->pack(static_cast<int>(e)); }
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CarlaManeuverType& e) { int n; b->unpack(n); e = static_cast<CarlaManeuverType>(n); }

/**
 * Class generated from <tt>carla/msg/CarlaManeuverMessage.msg:17</tt> by opp_msgtool.
 * <pre>
 * class CarlaManeuverMessage extends omnetpp::cPacket
 * {
 *     int msgType;            // CarlaManeuverType
 *     int senderId;           // OMNeT++ vehicle id (myId)
 *     int platoonId;          // logical platoon id
 *     int leaderId;           // leader id (typically 0)
 *     int joinerId;           // joiner id (for join-related messages)
 *     bool permitted = false; // JOIN_RSP
 *     double platoonSpeed = -1;   // m/s (MOVE_TO_POS / JOIN_FORMATION / UPDATE_FORMATION)
 *     int joinIndex = -1;         // insertion index (JoinAtBack uses end)
 *     int newFormation[];         // ordered ids: [leader, ..., tail]
 * }
 * </pre>
 */
class CarlaManeuverMessage : public ::omnetpp::cPacket
{
  protected:
    int msgType = 0;
    int senderId = 0;
    int platoonId = 0;
    int leaderId = 0;
    int joinerId = 0;
    bool permitted = false;
    double platoonSpeed = -1;
    int joinIndex = -1;
    int *newFormation = nullptr;
    size_t newFormation_arraysize = 0;

  private:
    void copy(const CarlaManeuverMessage& other);

  protected:
    bool operator==(const CarlaManeuverMessage&) = delete;

  public:
    CarlaManeuverMessage(const char *name=nullptr);
    CarlaManeuverMessage(const CarlaManeuverMessage& other);
    virtual ~CarlaManeuverMessage();
    CarlaManeuverMessage& operator=(const CarlaManeuverMessage& other);
    virtual CarlaManeuverMessage *dup() const override {return new CarlaManeuverMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getMsgType() const;
    virtual void setMsgType(int msgType);

    virtual int getSenderId() const;
    virtual void setSenderId(int senderId);

    virtual int getPlatoonId() const;
    virtual void setPlatoonId(int platoonId);

    virtual int getLeaderId() const;
    virtual void setLeaderId(int leaderId);

    virtual int getJoinerId() const;
    virtual void setJoinerId(int joinerId);

    virtual bool getPermitted() const;
    virtual void setPermitted(bool permitted);

    virtual double getPlatoonSpeed() const;
    virtual void setPlatoonSpeed(double platoonSpeed);

    virtual int getJoinIndex() const;
    virtual void setJoinIndex(int joinIndex);

    virtual void setNewFormationArraySize(size_t size);
    virtual size_t getNewFormationArraySize() const;
    virtual int getNewFormation(size_t k) const;
    virtual void setNewFormation(size_t k, int newFormation);
    virtual void insertNewFormation(size_t k, int newFormation);
    [[deprecated]] void insertNewFormation(int newFormation) {appendNewFormation(newFormation);}
    virtual void appendNewFormation(int newFormation);
    virtual void eraseNewFormation(size_t k);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CarlaManeuverMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CarlaManeuverMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline CarlaManeuverMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<CarlaManeuverMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __CARLAMANEUVERMESSAGE_M_H

